global:
  resolve_timeout: 5m
  telegram_api_url: "https://api.telegram.org"

receivers:
  - name: telegram-test
    telegram_configs:
  - chat_id: -4633675649
    bot_token: 7450568248:AAHEszsnN9w7_d0vHeARRbAW-Og_mZBqMD4
    api_url: "https://api.telegram.org"
    send_resolved: true

route:
  receiver: telegram-test
  group_wait: 15s
  group_interval: 30s
  repeat_interval: 12h
  routes:
    - receiver: telegram-test
      continue: true
      matchers:
        - severity="critical"